version: '3'

services:

  sonar:
    image: sonarqube:8.6-community
    container_name: ecoCode-sonar
    restart: unless-stopped
    volumes:
      - ./target/ecoCode-rules-1.0-SNAPSHOT.jar:/opt/sonarqube/extensions/plugins/ecoCode-rules-1.0-SNAPSHOT.jar
    ports:
      - 9000:9000
      - 9092:9092
